name: PAI Skill Enforcer
maintainer: jcfischer
status: shipped
created: 2026-01-31
type: tool
upstream: jcfischer/pai-skill-enforcer
paths:
  - hooks/SkillInvocationEnforcement.hook.ts

contributors:
  jcfischer:
    zone: maintainer
    since: 2026-01-31
