name: pai-secret-scanning
maintainer: jcfischer
status: shipped
type: infrastructure
source:
  repo: jcfischer/pai-secret-scanning
  branch: main
tests: bun test

contributors:
  jcfischer:
    zone: maintainer
    since: 2026-01-31
