name: PAI Signal
maintainer: mellanon
status: contrib-prep
created: 2026-01-31
type: skill
upstream: danielmiessler/PAI
fork: mellanon/PAI
contrib_branch: contrib/signal-v1.0.0
source_branch: feature/signal-agent-2
tag: signal-v1.0.0
paths:
  - Observability/
  - hooks/ToolUseInstrumentation.hook.ts
  - hooks/LoadContext.hook.ts
  - bin/ingest/
tests: bun test
docs: https://gist.github.com/mellanon/62a12ddef60ca7ff74331c2983fb43c7

contributors:
  mellanon:
    zone: maintainer
    since: 2026-01-31
