name: SpecFlow Lifecycle Extension
maintainer: mellanon
status: building
created: 2026-01-31
type: bundle
upstream: jcfischer/specflow-bundle
fork: mellanon/specflow-bundle
paths:
  - playbooks/ContribPrep/
  - playbooks/Review/
  - playbooks/Release/
  - templates/OPEN-SPEC.md

contributors:
  mellanon:
    zone: maintainer
    since: 2026-01-31
